"""Fail-closed, field-aware transformation boundary for evidence exports.

This module deliberately owns copies made for external or durable sinks.  It
never alters operational tool requests.  Production adapters must explicitly
call :class:`ExportBoundary`; an adapter cannot become covered merely by using
the same evidence object elsewhere.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import re
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass, field
from enum import StrEnum
from typing import TYPE_CHECKING, Any, Protocol

if TYPE_CHECKING:
    from ..execution.redaction import StreamRedactor

POLICY_SCHEMA_VERSION = "cops.export-policy/v1"
DETECTOR_VERSION = "cops-export-detectors/v1"
_SUPPORTED_ATTACHMENT_TYPES = frozenset({"text/plain", "application/json"})
_BLOCKED_PATH_COMPONENTS = frozenset({"chain_of_thought", "reasoning"})
_EMAIL_RE = re.compile(r"(?i)\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b")
_SSN_RE = re.compile(r"\b\d{3}-\d{2}-\d{4}\b")


class ExportRefused(RuntimeError):
    """A bounded export refusal which contains no source content."""


class ExportAction(StrEnum):
    ALLOW = "allow"
    REDACT = "redact"
    OMIT = "omit"
    PSEUDONYMIZE = "pseudonymize"


class Classification(StrEnum):
    PUBLIC = "public"
    INTERNAL = "internal"
    PERSONAL = "personal"
    RESTRICTED = "restricted"
    SECRET = "secret"  # noqa: S105 - classification label, never a credential


@dataclass(frozen=True)
class FieldRule:
    path: str
    classification: Classification
    action: ExportAction


def _rule_components(rule: FieldRule) -> tuple[str, ...]:
    return tuple(rule.path.split("."))


def _rules_overlap(left: tuple[str, ...], right: tuple[str, ...]) -> bool:
    return len(left) == len(right) and all(
        left_component == right_component or left_component == "*" or right_component == "*"
        for left_component, right_component in zip(left, right, strict=True)
    )


def _rule_matches_path(rule: tuple[str, ...], path: tuple[str, ...]) -> bool:
    """Return whether a field rule matches one concrete payload path."""

    return len(rule) == len(path) and all(
        rule_component == "*" or rule_component == path_component
        for rule_component, path_component in zip(rule, path, strict=True)
    )


def _rule_specificity(components: tuple[str, ...]) -> int:
    return sum(component != "*" for component in components)


@dataclass(frozen=True)
class DestinationRule:
    sink_id: str
    destination: str
    purpose: str
    permitted_classifications: frozenset[Classification]


@dataclass(frozen=True)
class ExportPolicy:
    """Validated v1 export policy.

    ``field_rules`` form an allowlist. ``*`` matches one component of a nested
    field path. The only information that can leave the boundary is specified by
    one of these rules or generated by the boundary itself.
    """

    policy_id: str
    version: str
    field_rules: tuple[FieldRule, ...]
    destinations: tuple[DestinationRule, ...]
    max_stream_bytes: int = 65_536
    max_attachment_bytes: int = 65_536
    max_attachments: int = 4
    max_payload_bytes: int = 65_536
    max_payload_depth: int = 16
    schema_version: str = POLICY_SCHEMA_VERSION

    def __post_init__(self) -> None:
        if self.schema_version != POLICY_SCHEMA_VERSION:
            raise ValueError("unsupported policy schema version")
        if not self.policy_id or not self.version:
            raise ValueError("policy id and version are required")
        limits = (
            self.max_stream_bytes,
            self.max_attachment_bytes,
            self.max_attachments,
            self.max_payload_bytes,
            self.max_payload_depth,
        )
        if any(type(limit) is not int or limit <= 0 for limit in limits):
            raise ValueError("export limits must be positive")
        if not self.destinations:
            raise ValueError("at least one destination is required")
        seen_destinations: set[tuple[str, str, str]] = set()
        for rule in self.destinations:
            key = (rule.sink_id, rule.destination, rule.purpose)
            if not all(key) or key in seen_destinations or not rule.permitted_classifications:
                raise ValueError("invalid or duplicate destination rule")
            seen_destinations.add(key)
        seen_paths: set[str] = set()
        validated_rules: list[tuple[FieldRule, tuple[str, ...]]] = []
        for rule in self.field_rules:
            components = _rule_components(rule)
            if not rule.path or rule.path in seen_paths or any(not item for item in components):
                raise ValueError("invalid or duplicate field rule")
            if _BLOCKED_PATH_COMPONENTS.intersection(components):
                raise ValueError("model reasoning fields cannot be exported")
            if any(
                _rules_overlap(components, existing_components)
                and _rule_specificity(components) == _rule_specificity(existing_components)
                for _, existing_components in validated_rules
            ):
                raise ValueError("ambiguous field rule overlap")
            seen_paths.add(rule.path)
            validated_rules.append((rule, components))

    @classmethod
    def from_mapping(cls, value: Mapping[str, Any]) -> ExportPolicy:
        """Create a policy from JSON-compatible data and reject unknown shapes."""
        allowed = {
            "schema_version",
            "policy_id",
            "version",
            "field_rules",
            "destinations",
            "limits",
        }
        if set(value) - allowed:
            raise ValueError("policy contains unsupported keys")
        limits = value.get("limits", {})
        if not isinstance(limits, Mapping):
            raise ValueError("policy limits must be an object")
        if set(limits) - {
            "max_stream_bytes",
            "max_attachment_bytes",
            "max_attachments",
            "max_payload_bytes",
            "max_payload_depth",
        }:
            raise ValueError("policy contains unsupported limits")
        try:
            raw_fields = value["field_rules"]
            raw_destinations = value["destinations"]
            if not isinstance(raw_fields, Sequence) or isinstance(raw_fields, (str, bytes)):
                raise ValueError("field rules must be an array")
            if not isinstance(raw_destinations, Sequence) or isinstance(raw_destinations, (str, bytes)):
                raise ValueError("destinations must be an array")
            if any(
                not isinstance(item, Mapping)
                or set(item) != {"path", "classification", "action"}
                or not all(isinstance(item[name], str) for name in ("path", "classification", "action"))
                for item in raw_fields
            ):
                raise ValueError("field rules have an invalid shape")
            if any(
                not isinstance(item, Mapping)
                or set(item) != {"sink_id", "destination", "purpose", "permitted_classifications"}
                or not all(isinstance(item[name], str) for name in ("sink_id", "destination", "purpose"))
                or not isinstance(item["permitted_classifications"], Sequence)
                or isinstance(item["permitted_classifications"], (str, bytes))
                or not all(isinstance(classification, str) for classification in item["permitted_classifications"])
                for item in raw_destinations
            ):
                raise ValueError("destinations have an invalid shape")
            fields = tuple(
                FieldRule(
                    path=str(item["path"]),
                    classification=Classification(item["classification"]),
                    action=ExportAction(item["action"]),
                )
                for item in raw_fields
            )
            destinations = tuple(
                DestinationRule(
                    sink_id=str(item["sink_id"]),
                    destination=str(item["destination"]),
                    purpose=str(item["purpose"]),
                    permitted_classifications=frozenset(
                        Classification(classification) for classification in item["permitted_classifications"]
                    ),
                )
                for item in raw_destinations
            )
            parsed_limits: dict[str, int] = {}
            for name, default in (
                ("max_stream_bytes", 65_536),
                ("max_attachment_bytes", 65_536),
                ("max_attachments", 4),
                ("max_payload_bytes", 65_536),
                ("max_payload_depth", 16),
            ):
                candidate = limits.get(name, default)
                if type(candidate) is not int:
                    raise ValueError("policy limits must be integers")
                parsed_limits[name] = candidate
            return cls(
                schema_version=str(value["schema_version"]),
                policy_id=str(value["policy_id"]),
                version=str(value["version"]),
                field_rules=fields,
                destinations=destinations,
                **parsed_limits,
            )
        except (KeyError, TypeError, ValueError):
            raise ValueError("invalid export policy") from None

    def destination_rule(self, descriptor: SinkDescriptor) -> DestinationRule:
        for rule in self.destinations:
            if (
                rule.sink_id == descriptor.sink_id
                and rule.destination == descriptor.destination
                and rule.purpose == descriptor.purpose
            ):
                return rule
        raise ExportRefused("unregistered_destination")

    def rule_for(self, path: tuple[str, ...]) -> FieldRule | None:
        matches = [
            (rule, _rule_components(rule))
            for rule in self.field_rules
            if _rule_matches_path(_rule_components(rule), path)
        ]
        if not matches:
            return None
        greatest_specificity = max(_rule_specificity(components) for _, components in matches)
        best_matches = [rule for rule, components in matches if _rule_specificity(components) == greatest_specificity]
        if len(best_matches) != 1:
            raise ExportRefused("ambiguous_field_policy")
        return best_matches[0]


@dataclass(frozen=True)
class SinkDescriptor:
    """Stable declaration of the recipient selected by an adapter."""

    sink_id: str
    destination: str
    purpose: str


class ExportSink(Protocol):
    descriptor: SinkDescriptor

    def send(self, export: SanitizedExport) -> None: ...


@dataclass(frozen=True)
class Attachment:
    content_type: str
    chunks: Iterable[bytes | str]


@dataclass(frozen=True)
class SanitizedAttachment:
    ordinal: int
    content_type: str
    content: bytes


@dataclass(frozen=True)
class ExportAudit:
    schema_version: str
    policy_id: str
    policy_version: str
    destination: str
    purpose: str
    transformations: Mapping[str, int]
    restricted_evidence_reference_sha256: str | None
    detector_version: str = DETECTOR_VERSION


@dataclass(frozen=True)
class SanitizedExport:
    payload: Mapping[str, Any]
    text: str | None
    attachments: tuple[SanitizedAttachment, ...]
    audit: ExportAudit


@dataclass(frozen=True)
class CorpusMetrics:
    policy_version: str
    detector_version: str
    records: int
    sensitive_fields: int
    missed_sensitive_fields: int
    unnecessary_redactions: int
    unsupported_cases: int


@dataclass
class _TransformState:
    counts: dict[str, int] = field(
        default_factory=lambda: {"allowed": 0, "redacted": 0, "omitted": 0, "pseudonymized": 0}
    )
    input_bytes: int = 0


class ExportBoundary:
    """Transform a bounded evidence copy before delivery to one declared sink."""

    def __init__(self, policy: ExportPolicy, *, pseudonym_key: bytes, redactor: StreamRedactor | None = None) -> None:
        if not pseudonym_key:
            raise ValueError("pseudonym key is required")
        self.policy = policy
        self._pseudonym_key = pseudonym_key
        if redactor is None:
            # ``cops.execution`` imports contract models, which in turn import
            # evidence. Delay this optional runtime dependency until a caller
            # constructs the boundary so evidence remains safe to import from
            # the contracts layer.
            from ..execution.redaction import StreamRedactor

            redactor = StreamRedactor()
        self._redactor = redactor

    def export(
        self,
        sink: ExportSink,
        payload: Mapping[str, Any],
        *,
        text_chunks: Iterable[bytes | str] | None = None,
        attachments: Sequence[Attachment] = (),
        restricted_evidence_reference: str | None = None,
        pseudonym_scope: str,
    ) -> SanitizedExport:
        """Send exactly one fully inspected export or refuse before calling ``sink``."""
        try:
            descriptor = sink.descriptor
            destination_rule = self.policy.destination_rule(descriptor)
            state = _TransformState()
            transformed_payload = self._transform_mapping(
                payload, (), destination_rule, pseudonym_scope, state, depth=0, ancestors=set()
            )
            if (
                len(json.dumps(transformed_payload, sort_keys=True, separators=(",", ":")).encode("utf-8"))
                > self.policy.max_payload_bytes
            ):
                raise ExportRefused("structured_payload_size_exceeded")
            text = None
            if text_chunks is not None:
                text = self._transform_stream(text_chunks, ("text",), destination_rule, pseudonym_scope, state)
            transformed_attachments = self._transform_attachments(attachments, destination_rule, pseudonym_scope, state)
            reference_digest = _reference_digest(restricted_evidence_reference)
            audit = ExportAudit(
                schema_version=self.policy.schema_version,
                policy_id=self.policy.policy_id,
                policy_version=self.policy.version,
                destination=descriptor.destination,
                purpose=descriptor.purpose,
                transformations=dict(state.counts),
                restricted_evidence_reference_sha256=reference_digest,
            )
            sanitized = SanitizedExport(
                payload=transformed_payload,
                text=text,
                attachments=transformed_attachments,
                audit=audit,
            )
        except ExportRefused:
            raise
        except Exception:
            raise ExportRefused("policy_transformation_refused") from None
        try:
            sink.send(sanitized)
        except Exception:
            raise ExportRefused("sanitized_sink_delivery_failed") from None
        return sanitized

    def _transform_mapping(
        self,
        value: Mapping[str, Any],
        path: tuple[str, ...],
        destination: DestinationRule,
        scope: str,
        state: _TransformState,
        *,
        depth: int,
        ancestors: set[int],
    ) -> dict[str, Any]:
        if not isinstance(value, Mapping):
            raise ExportRefused("structured_payload_invalid")
        if depth > self.policy.max_payload_depth:
            raise ExportRefused("structured_payload_depth_exceeded")
        self._charge_input_bytes(2, state)
        object_id = id(value)
        if object_id in ancestors:
            raise ExportRefused("structured_payload_cycle")
        ancestors.add(object_id)
        output: dict[str, Any] = {}
        try:
            for key, item in value.items():
                if not isinstance(key, str) or key in _BLOCKED_PATH_COMPONENTS:
                    state.counts["omitted"] += 1
                    continue
                self._charge_input_value(key, state)
                transformed = self._transform_value(
                    item, path + (key,), destination, scope, state, depth=depth + 1, ancestors=ancestors
                )
                if transformed is not _OMITTED:
                    output[key] = transformed
        finally:
            ancestors.remove(object_id)
        return output

    def _transform_value(
        self,
        value: Any,
        path: tuple[str, ...],
        destination: DestinationRule,
        scope: str,
        state: _TransformState,
        *,
        depth: int,
        ancestors: set[int],
    ) -> Any:
        if any(component in _BLOCKED_PATH_COMPONENTS for component in path):
            state.counts["omitted"] += 1
            return _OMITTED
        if isinstance(value, Mapping):
            output = self._transform_mapping(value, path, destination, scope, state, depth=depth, ancestors=ancestors)
            return output if output else _OMITTED
        if isinstance(value, list | tuple):
            if depth > self.policy.max_payload_depth:
                raise ExportRefused("structured_payload_depth_exceeded")
            self._charge_input_bytes(2, state)
            object_id = id(value)
            if object_id in ancestors:
                raise ExportRefused("structured_payload_cycle")
            ancestors.add(object_id)
            output = []
            try:
                for item in value:
                    transformed = self._transform_value(
                        item, path + ("*",), destination, scope, state, depth=depth + 1, ancestors=ancestors
                    )
                    if transformed is not _OMITTED:
                        output.append(transformed)
            finally:
                ancestors.remove(object_id)
            return output if output else _OMITTED
        if value is not None and not isinstance(value, str | int | float | bool):
            raise ExportRefused("structured_value_unsupported")
        self._charge_input_value(value, state)
        rule = self.policy.rule_for(path)
        if rule is None:
            state.counts["omitted"] += 1
            return _OMITTED
        if rule.action is ExportAction.OMIT:
            state.counts["omitted"] += 1
            return _OMITTED
        if rule.action is ExportAction.REDACT:
            state.counts["redacted"] += 1
            return f"[REDACTED:{rule.classification.upper()}]"
        if rule.action is ExportAction.PSEUDONYMIZE:
            state.counts["pseudonymized"] += 1
            return self._pseudonymize(value, scope)
        if rule.classification not in destination.permitted_classifications:
            state.counts["omitted"] += 1
            return _OMITTED
        state.counts["allowed"] += 1
        return self._sanitize_text(value) if isinstance(value, str) else value

    def _charge_input_value(self, value: Any, state: _TransformState) -> None:
        try:
            encoded = json.dumps(value, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
        except (TypeError, ValueError, UnicodeError, OverflowError):
            raise ExportRefused("structured_payload_invalid") from None
        self._charge_input_bytes(len(encoded), state)

    def _charge_input_bytes(self, size: int, state: _TransformState) -> None:
        state.input_bytes += size
        if state.input_bytes > self.policy.max_payload_bytes:
            raise ExportRefused("structured_payload_size_exceeded")

    def _transform_stream(
        self,
        chunks: Iterable[bytes | str],
        path: tuple[str, ...],
        destination: DestinationRule,
        scope: str,
        state: _TransformState,
    ) -> str:
        raw = _read_bounded_utf8(chunks, self.policy.max_stream_bytes, "stream")
        transformed = self._transform_value(raw, path, destination, scope, state, depth=1, ancestors=set())
        if transformed is _OMITTED:
            raise ExportRefused("text_not_permitted")
        if not isinstance(transformed, str):
            raise ExportRefused("text_transformation_invalid")
        return transformed

    def _transform_attachments(
        self,
        attachments: Sequence[Attachment],
        destination: DestinationRule,
        scope: str,
        state: _TransformState,
    ) -> tuple[SanitizedAttachment, ...]:
        if len(attachments) > self.policy.max_attachments:
            raise ExportRefused("attachment_count_exceeded")
        transformed: list[SanitizedAttachment] = []
        for ordinal, attachment in enumerate(attachments, start=1):
            if attachment.content_type not in _SUPPORTED_ATTACHMENT_TYPES:
                raise ExportRefused("attachment_type_unsupported")
            raw = _read_bounded_utf8(attachment.chunks, self.policy.max_attachment_bytes, "attachment")
            value = self._transform_value(
                raw, ("attachment", "content"), destination, scope, state, depth=1, ancestors=set()
            )
            if value is _OMITTED or not isinstance(value, str):
                raise ExportRefused("attachment_not_permitted")
            transformed.append(
                SanitizedAttachment(
                    ordinal=ordinal, content_type=attachment.content_type, content=value.encode("utf-8")
                )
            )
        return tuple(transformed)

    def _sanitize_text(self, value: str) -> str:
        redacted = self._redactor.redact(value)
        redacted = _EMAIL_RE.sub("[REDACTED:EMAIL]", redacted)
        return _SSN_RE.sub("[REDACTED:SSN]", redacted)

    def _pseudonymize(self, value: Any, scope: str) -> str:
        if not scope:
            raise ExportRefused("pseudonym_scope_required")
        material = f"{scope}\x00{value}".encode()
        digest = hmac.new(self._pseudonym_key, material, hashlib.sha256).hexdigest()[:24]
        return f"pseudonym-v1:{digest}"


_OMITTED = object()


def _read_bounded_utf8(chunks: Iterable[bytes | str], limit: int, kind: str) -> str:
    pieces: list[bytes] = []
    size = 0
    try:
        for chunk in chunks:
            if isinstance(chunk, str):
                encoded = chunk.encode("utf-8")
            elif isinstance(chunk, bytes):
                encoded = chunk
            else:
                raise ExportRefused(f"{kind}_chunk_unsupported")
            size += len(encoded)
            if size > limit:
                raise ExportRefused(f"{kind}_size_exceeded")
            pieces.append(encoded)
        return b"".join(pieces).decode("utf-8", errors="strict")
    except ExportRefused:
        raise
    except Exception:
        raise ExportRefused(f"{kind}_incomplete") from None


def _reference_digest(reference: str | None) -> str | None:
    if reference is None:
        return None
    if not reference or len(reference) > 512:
        raise ExportRefused("restricted_reference_invalid")
    return hashlib.sha256(reference.encode("utf-8")).hexdigest()


def evaluate_privacy_corpus(
    policy: ExportPolicy,
    corpus: Sequence[Mapping[str, Any]],
    *,
    pseudonym_key: bytes,
) -> CorpusMetrics:
    """Measure policy coverage using a synthetic, labelled corpus only.

    Each case supplies ``payload``, ``sensitive_paths``, and ``benign_paths``.
    This measurement is intentionally limited to declared labels and cannot
    prove detection of arbitrary private data.
    """
    boundary = ExportBoundary(policy, pseudonym_key=pseudonym_key)
    destination = policy.destinations[0]
    sink = _CorpusSink(SinkDescriptor(destination.sink_id, destination.destination, destination.purpose))
    missed = unnecessary = sensitive = unsupported = 0
    for case in corpus:
        try:
            export = boundary.export(sink, case["payload"], pseudonym_scope="synthetic-corpus")
        except (ExportRefused, KeyError, TypeError):
            unsupported += 1
            continue
        sensitive_paths = tuple(str(item) for item in case.get("sensitive_paths", ()))
        benign_paths = tuple(str(item) for item in case.get("benign_paths", ()))
        sensitive += len(sensitive_paths)
        for path in sensitive_paths:
            path_components = tuple(path.split("."))
            exported = _lookup_path(export.payload, path_components)
            source = _lookup_path(case["payload"], path_components)
            if exported is not _OMITTED and exported == source:
                missed += 1
        for path in benign_paths:
            path_components = tuple(path.split("."))
            source = _lookup_path(case["payload"], path_components)
            exported = _lookup_path(export.payload, path_components)
            if exported is _OMITTED or exported != source:
                unnecessary += 1
    return CorpusMetrics(
        policy_version=policy.version,
        detector_version=DETECTOR_VERSION,
        records=len(corpus),
        sensitive_fields=sensitive,
        missed_sensitive_fields=missed,
        unnecessary_redactions=unnecessary,
        unsupported_cases=unsupported,
    )


class _CorpusSink:
    def __init__(self, descriptor: SinkDescriptor) -> None:
        self.descriptor = descriptor

    def send(self, export: SanitizedExport) -> None:
        del export


def _lookup_path(value: Mapping[str, Any], path: tuple[str, ...]) -> Any:
    current: Any = value
    for component in path:
        if not isinstance(current, Mapping) or component not in current:
            return _OMITTED
        current = current[component]
    return current
