"""COPS passive and active asset discovery, service identification, and infrastructure assessment runtime."""

from __future__ import annotations

from .active_models import (
    ActiveScanSession,
    ActiveServiceAssessment,
    ConfidenceLevel,
    InferredFingerprint,
    ObservedConfiguration,
    ObservedTLS,
    PortState,
    Protocol,
    ScanBudget,
    ScanDelta,
    ScanVantage,
    ServiceReachability,
    TargetShiftQuarantine,
)
from .active_scanner import (
    ActiveScanError,
    ActiveScanner,
    OfflineSyntheticDispatcher,
    ProbeDispatcher,
    ScopeViolationError,
    StandardSocketDispatcher,
    compare_active_scans,
)
from .cli import build_discovery_parser, command_discovery
from .fingerprinter import infer_service_fingerprint
from .importer import import_masscan_json, import_nmap_xml
from .infra_collector import (
    DEFAULT_INFRA_PORTS,
    InfraCollector,
    OfflineSyntheticInfraCollector,
    StandardSocketInfraCollector,
    assess_infrastructure_services,
)
from .infra_models import (
    AuthPrerequisite,
    IdentityAttackPathCandidate,
    IdentityAttackPathType,
    InfraAssessmentReport,
    InfraServiceAssessment,
    InfraServiceType,
    ServiceExposureStatus,
)
from .merger import merge_inventories, merge_two_assets
from .models import (
    AssetType,
    DiscoveredAsset,
    DiscoveryInventory,
    EvidenceProvenance,
    QuarantineReason,
    ReconciliationStatus,
)
from .normalizers import (
    normalize_certificate_record,
    normalize_cloud_export,
    normalize_dns_record,
    normalize_endpoint_record,
    normalize_ip_record,
)
from .reconciler import reconcile_asset, reconcile_inventory
from .data_collector import (
    DEFAULT_DATA_PORTS,
    DataServicesCollector,
    OfflineSyntheticDataCollector,
    StandardSocketDataCollector,
    assess_data_services,
)
from .data_models import (
    DataAuthPrerequisite,
    DataExposureStatus,
    DataPrivilegeCandidate,
    DataPrivilegeImpact,
    DataServiceAssessment,
    DataServiceCategory,
    DataServicesReport,
    DataServiceType,
)
from .remote_collector import (
    DEFAULT_REMOTE_PORTS,
    OfflineSyntheticRemoteCollector,
    RemoteServicesCollector,
    StandardSocketRemoteCollector,
    assess_remote_services,
)
from .remote_models import (
    CleanupReceipt,
    HostPrivilegeCandidate,
    LateralMovementImpact,
    RemoteAuthPrerequisite,
    RemoteExposureStatus,
    RemoteServiceAssessment,
    RemoteServiceCategory,
    RemoteServicesReport,
    RemoteServiceType,
)

from .messaging_collector import (
    DEFAULT_MESSAGING_PORTS,
    MessagingServicesCollector,
    OfflineSyntheticMessagingCollector,
    StandardSocketMessagingCollector,
    assess_messaging_services,
)
from .messaging_models import (
    MessagingAuthPrerequisite,
    MessagingCategory,
    MessagingExposureStatus,
    MessagingPrivilegeCandidate,
    MessagingPrivilegeImpact,
    MessagingServiceAssessment,
    MessagingServicesReport,
    MessagingServiceType,
)


__all__ = [
    "ActiveScanError",
    "ActiveScanSession",
    "ActiveScanner",
    "ActiveServiceAssessment",
    "AssetType",
    "AuthPrerequisite",
    "ConfidenceLevel",
    "DEFAULT_INFRA_PORTS",
    "DiscoveredAsset",
    "DiscoveryInventory",
    "EvidenceProvenance",
    "IdentityAttackPathCandidate",
    "IdentityAttackPathType",
    "InferredFingerprint",
    "InfraAssessmentReport",
    "InfraCollector",
    "InfraServiceAssessment",
    "InfraServiceType",
    "ObservedConfiguration",
    "ObservedTLS",
    "OfflineSyntheticDispatcher",
    "OfflineSyntheticInfraCollector",
    "PortState",
    "ProbeDispatcher",
    "Protocol",
    "QuarantineReason",
    "ReconciliationStatus",
    "ScanBudget",
    "ScanDelta",
    "ScanVantage",
    "ScopeViolationError",
    "ServiceExposureStatus",
    "ServiceReachability",
    "StandardSocketDispatcher",
    "StandardSocketInfraCollector",
    "TargetShiftQuarantine",
    "assess_infrastructure_services",
    "build_discovery_parser",
    "command_discovery",
    "compare_active_scans",
    "import_masscan_json",
    "import_nmap_xml",
    "infer_service_fingerprint",
    "merge_inventories",
    "merge_two_assets",
    "normalize_certificate_record",
    "normalize_cloud_export",
    "normalize_dns_record",
    "normalize_endpoint_record",
    "normalize_ip_record",
    "reconcile_asset",
    "reconcile_inventory",
    "DEFAULT_REMOTE_PORTS",
    "CleanupReceipt",
    "HostPrivilegeCandidate",
    "LateralMovementImpact",
    "OfflineSyntheticRemoteCollector",
    "RemoteAuthPrerequisite",
    "RemoteExposureStatus",
    "RemoteServiceAssessment",
    "RemoteServiceCategory",
    "RemoteServicesCollector",
    "RemoteServicesReport",
    "RemoteServiceType",
    "StandardSocketRemoteCollector",
    "assess_remote_services",
    "DEFAULT_DATA_PORTS",
    "DataAuthPrerequisite",
    "DataExposureStatus",
    "DataPrivilegeCandidate",
    "DataPrivilegeImpact",
    "DataServiceAssessment",
    "DataServiceCategory",
    "DataServicesCollector",
    "DataServicesReport",
    "DataServiceType",
    "OfflineSyntheticDataCollector",
    "StandardSocketDataCollector",
    "assess_data_services",
    "DEFAULT_MESSAGING_PORTS",
    "MessagingAuthPrerequisite",
    "MessagingCategory",
    "MessagingExposureStatus",
    "MessagingPrivilegeCandidate",
    "MessagingPrivilegeImpact",
    "MessagingServiceAssessment",
    "MessagingServiceType",
    "MessagingServicesCollector",
    "MessagingServicesReport",
    "OfflineSyntheticMessagingCollector",
    "StandardSocketMessagingCollector",
    "assess_messaging_services",
]
